// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "github.com/arpsch/players/model"

// ClientRunner is an autogenerated mock type for the ClientRunner type
type ClientRunner struct {
	mock.Mock
}

// GetTeamInformationByID provides a mock function with given fields: ctx, teamID
func (_m *ClientRunner) GetTeamInformationByID(ctx context.Context, teamID string) (string, []model.Player, error) {
	ret := _m.Called(ctx, teamID)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 []model.Player
	if rf, ok := ret.Get(1).(func(context.Context, string) []model.Player); ok {
		r1 = rf(ctx, teamID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]model.Player)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, teamID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
